### ISSUE TITLE
Cannot figure out nested hash statements in traefik::config::section

### ISSUE THREAD

**Issue by Yggdrasil** [praekeltfoundation/puppet-traefik#12]
Thanks for your excellent module. It's very useful.

I'm hoping you can help me understand how to create a part of the traefik.toml config file. I can get most sections set up correctly, except the nested parts.

I can't figure out how to turn something like this...
```
[entryPoints]
  [entryPoints.http]
  address = ":80"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
```
... into the matching Puppet code.

I'm not too familiar with the hash notation in Puppet and Googling got me nowhere.

The following *didn't* work:
```
  traefik::config::section { 'entryPoints':
    hash => {
      'entryPoints.http'  => {
        'address'         => ':80',
      },
      'entryPoints.https' => {
        'address'         => ':443',
      }
    }
  }
```
It resulted in:
```
[entryPoints."entryPoints.http"]
address = ":80"
[entryPoints."entryPoints.https"]
address = ":443"
```

Could you give me a hint please? Thanks!

**Comment by JayH5** [comment]
The Puppet hash syntax is quite similar to something like JSON just with `=>`s. What gets me confused is the TOML hashes/tables. For a table `[x.y.z]` it's actually a nested hash, so
```puppet
'x' => { 'y' => { 'z' => {} }}
```
Additionally, the name of the Puppet resource is used for the top-level of the resulting hash.. so:
```puppet
traefik::config::section { 'x':
  hash => {
    'y' => {
      'z' => {}
    }
  }
}
```

So that config of yours would be:
```puppet
traefik::config::section { 'entryPoints':
  hash => {
    'http'  => {
      'address'  => ':80'
    },
    'https' => {
      'address' => ':443',
      'tls'     => {}
    }
  }
}
```

It's a bit confusing :/ but it's the best I could come up with quickly for generating TOML.

**Comment by Yggdrasil** [comment]
Thanks so much! That works very well, including the empty 'tls' key creating a new empty table. Perfect. I'm succesfully using the module in production now.
